// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMnkUoWGTtNp-gIYBqZ1FnKq0Jv2iUaG4',
    appId: '1:671660766414:web:d496b1fb5fcb5d901a8c9f',
    messagingSenderId: '671660766414',
    projectId: 'udemy-project-7bedb',
    authDomain: 'udemy-project-7bedb.firebaseapp.com',
    databaseURL: 'https://udemy-project-7bedb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'udemy-project-7bedb.appspot.com',
    measurementId: 'G-FX97HJWBTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe3OVrRDy7bFNA1nOGm11LxFlg-iQVUNc',
    appId: '1:671660766414:android:629436379dea986e1a8c9f',
    messagingSenderId: '671660766414',
    projectId: 'udemy-project-7bedb',
    databaseURL: 'https://udemy-project-7bedb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'udemy-project-7bedb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbvEc2ydy6oDVvRK2xjkUPXRPySPpxOrk',
    appId: '1:671660766414:ios:df2acd2b736813341a8c9f',
    messagingSenderId: '671660766414',
    projectId: 'udemy-project-7bedb',
    databaseURL: 'https://udemy-project-7bedb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'udemy-project-7bedb.appspot.com',
    iosClientId: '671660766414-f6nm83k762kd23si9ghpgjeimubhl3pt.apps.googleusercontent.com',
    iosBundleId: 'com.example.udemyLessons',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbvEc2ydy6oDVvRK2xjkUPXRPySPpxOrk',
    appId: '1:671660766414:ios:df2acd2b736813341a8c9f',
    messagingSenderId: '671660766414',
    projectId: 'udemy-project-7bedb',
    databaseURL: 'https://udemy-project-7bedb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'udemy-project-7bedb.appspot.com',
    iosClientId: '671660766414-f6nm83k762kd23si9ghpgjeimubhl3pt.apps.googleusercontent.com',
    iosBundleId: 'com.example.udemyLessons',
  );
}
